---
- name: create install dir
  file: path=/tmp/install_chrome state=directory
- name: download chrome
  command:  "wget -O /tmp/install_chrome/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
- name: make sure we have gdebi
  apt: pkg=gdebi-core
  sudo: true
- name: install chrome
  command: gdebi -n /tmp/install_chrome/chrome.deb
  sudo: true
- name: clean up
  file: path=/tmp/install_chrome state=absent
