---
- name: Remove yucky packages
  apt: pkg={{ item }} state=absent purge=yes  
  with_items:
    - unity-lens-music
    - unity-lens-photos
    - unity-lens-shopping
    - unity-lens-video
    - unity-scope-musicstores
    - thunderbird
    - totem
    - evolution
    - evolution-common
    - evolution-plugins
    - empathy
    - jayatana
