---
- name: check if RVM is installed
  stat: path=~/.rvm
  register: st
- name: make sure curl is installed
  apt: pkg=curl
  sudo: true
- name: Install RVM if it isn't installed
  shell: "\\curl -L https://get.rvm.io | bash -s stable --ruby"
  when: not st.stat.exists
- name: double check if RVM is installed
  stat: path=~/.rvm
  register: st
- name: Fail if RVM isn't installed
  fail: msg=RVM isn't installed {{ st }}
  when: not st.stat.exists

